name: Test-GitHub-Actions
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: make install
    steps:
      - name: my-step
        run: make lint